"""empty message

Revision ID: 0d67719241d6
Revises: 
Create Date: 2025-05-07 17:17:01.305272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d67719241d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('People',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('gender', sa.String(length=45), nullable=False),
    sa.Column('skin_color', sa.String(length=45), nullable=False),
    sa.Column('hair_color', sa.String(length=45), nullable=False),
    sa.Column('height', sa.String(length=45), nullable=False),
    sa.Column('eye_color', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('diameter', sa.Integer(), nullable=True),
    sa.Column('rotation_period', sa.String(length=45), nullable=True),
    sa.Column('terrain', sa.String(length=45), nullable=True),
    sa.Column('gravity', sa.Integer(), nullable=True),
    sa.Column('orbital_period', sa.String(length=45), nullable=True),
    sa.Column('population', sa.String(length=45), nullable=True),
    sa.Column('climate', sa.String(length=45), nullable=True),
    sa.Column('surface_water', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('Favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('People_id', sa.Integer(), nullable=True),
    sa.Column('Planets_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['People_id'], ['People.id'], ),
    sa.ForeignKeyConstraint(['Planets_id'], ['Planets.id'], ),
    sa.ForeignKeyConstraint(['User_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User_has_People',
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('People_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['People_id'], ['People.id'], ),
    sa.ForeignKeyConstraint(['User_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('User_id', 'People_id')
    )
    op.create_table('User_has_Planets',
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('Planets_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Planets_id'], ['Planets.id'], ),
    sa.ForeignKeyConstraint(['User_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('User_id', 'Planets_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User_has_Planets')
    op.drop_table('User_has_People')
    op.drop_table('Favorites')
    op.drop_table('User')
    op.drop_table('Planets')
    op.drop_table('People')
    # ### end Alembic commands ###
