"""empty message

Revision ID: 509bcaba2911
Revises: ca3dd5bd1b49
Create Date: 2025-05-07 14:22:57.960849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '509bcaba2911'
down_revision = 'ca3dd5bd1b49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Favorites', schema=None) as batch_op:
        batch_op.alter_column('People_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('Planets_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Favorites', schema=None) as batch_op:
        batch_op.alter_column('Planets_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('People_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
